Feature-admin-ui
Scott-Coates-Org/group-project-team-sapphire pull request #45
Opened 2022-09-14 17:06 UTC by m-oniqu3

2022-09-14 17:09 UTC, m-oniqu3 commented
Added navbar and sidebar as per #8

2022-09-14 18:18 UTC, perennialAutodidact requested changes
The functionality of the components is awesome! I like the changing menu icon and transition as it opens. I recently built a React hook which can detect clicks outside of an element which would be useful for closing the admin dropdown in the upper right, if you'd like to use it.

 I think a lot of the styling could be simplified with Bootstrap classes and overriding Bootstrap variables. Bootstrap has classes for margin, padding, borders, flex box, gaps, etc and they're all designed to be consistent and play well with each other responsively.

It doesn't appear that we can place any content to the right of the side bar. Anything added to App.js goes above or below the Admin div. If I put the side nav and some content in a parent div with `display: flex;`, the side nav doesn't open anymore. The side nav should also perhaps be `position: absolute;` otherwise it'll shove the content over and that might look a little awkward.

I also noticed a `package-lock.json` file got created by npm. I'm not sure if this will cause issues down the line, but the README says to use yarn instead of npm.

Overall it looks excellent and works well. With some minor tweaks I think these navs will be perfect! :smile: Great job!

2022-09-14 18:18 UTC, perennialAutodidact commented on src/components/helpers/wrapper/Container.module.scss
> +.container {
I think we should use Bootstrap's `container` or `container-fluid` classes for this. It will respond better with the `row` and `col` classes for responsive design

2022-09-14 18:18 UTC, perennialAutodidact commented on src/components/helpers/wrapper/Container.jsx
> +  return <div className={styled.container}>{props.children}</div>;
Bootstrap's container class does essentially the same thing. 
```
<div className="container"> {children} </div> 
```

2022-09-14 18:18 UTC, perennialAutodidact commented on src/components/admin/nav/SidebarItem.module.scss
> +  @include m.flex;
Bootstrap has flexbox classes built in `d-flex`, `flex-column`, `justify-content-center`, `align-items-center`, etc.

2022-09-14 18:18 UTC, perennialAutodidact commented on src/components/admin/nav/SidebarItem.module.scss
> +}
Bootstrap has classes for all of these.

2022-09-14 18:18 UTC, perennialAutodidact commented on src/components/admin/nav/Navbar.module.scss
> +      background: #ccc;
It might make sense to have the background color set via Sass variables. If they're added to the `$custom-colors` mapping in `team-sapphire-variables.scss` then they can be used within Bootstrap. 

```scss
// team-sapphire-variables
$some-color: #123123;
$custom-colors: (
      'my-custom-color': $some-color
);
```

```html
<div className="bg-my-custom-color"></div>
```

2022-09-14 18:18 UTC, perennialAutodidact commented on src/App.scss
> +  font-family: v.$text;
Bootstrap has variables for setting font family. 

```scss
// team-sapphire-variables.scss
$font1: 'some font', sans-serif;
$font2: 'some other font', sans-serif;

// override bootstrap variables
$font-family-base: $font1;
$headings-font-family: $font2;
```
Then bootstrap should pick them up in `bootstrap-setup.scss` and use them globally

2022-09-14 18:18 UTC, perennialAutodidact commented on package.json
> +    "style-loader": "^3.3.1"
I think 'css-loader' and 'style-loader' are included in React. I believe the error that happened before these were installed was caused by me. I loaded the bootstrap modules in the wrong order and it caused some issues. This should be fixed on the main branch now.

2022-09-14 18:18 UTC, perennialAutodidact commented on src/components/admin/nav/Sidebar.module.scss
> +  border-right: 1px solid #ccc;
Bootstrap has border classes

2022-09-14 18:18 UTC, perennialAutodidact commented on src/styles/_team-sapphire-variables.scss
> +$heading: "Roboto", sans-serif;
I mentioned it elsewhere, but we can override bootstrap variables with these.

2022-09-14 18:19 UTC, perennialAutodidact commented on src/components/helpers/wrapper/Container.jsx
> +  return <div className={styled.container}>{props.children}</div>;
This could also be done on an as-need basis without the need for a Container component

2022-09-14 18:48 UTC, m-oniqu3 commented on src/components/helpers/wrapper/Container.jsx
> +  return <div className={styled.container}>{props.children}</div>;
Okay noted, I'll make the changes

2022-09-14 18:49 UTC, m-oniqu3 commented on src/components/admin/nav/SidebarItem.module.scss
> +  @include m.flex;
Alright, I'll include those then

2022-09-14 18:49 UTC, m-oniqu3 commented on src/components/helpers/wrapper/Container.module.scss
> +.container {
Okay, I'll fix that

2022-09-14 18:53 UTC, m-oniqu3 commented on package.json
> +    "style-loader": "^3.3.1"
I totally forgot about the yarn rule, my apologies, since you fixed the error, i can delete them when its merged

2022-09-14 19:53 UTC, waldothedeveloper commented on package.json
> +    "react-icons": "^4.4.0",
Wow, I  didn't know that package existed, it's so cool!!! 
https://react-icons.github.io/react-icons

2022-09-14 20:00 UTC, m-oniqu3 commented on package.json
> +    "react-icons": "^4.4.0",
Yeah, react-icons is awesome, you get to import icons just like a component!

2022-09-15 00:57 UTC, m-oniqu3 commented on src/components/admin/nav/Sidebar.module.scss
> +  border-right: 1px solid #ccc;
Noted

2022-09-15 01:53 UTC, m-oniqu3 commented on src/components/admin/nav/SidebarItem.module.scss
> +}
Noted

2022-09-15 16:18 UTC, perennialAutodidact commented on src/components/admin/nav/Navbar.module.scss
> +    font-family: v.$heading;
I'll look into overriding the Bootstrap heading variable so all headings will get this font.

2022-09-15 16:24 UTC, m-oniqu3 commented on src/components/admin/nav/Navbar.module.scss
> +    font-family: v.$heading;
I did override them, using the bootstrap variables

2022-09-15 17:40 UTC, perennialAutodidact approved these changes
I think this iteration is going to work much better for us. I like the admin side nav being open on large screens and invisible on small screens.

2022-09-15 17:40 UTC, perennialAutodidact commented on src/components/admin/nav/Navbar.module.scss
> +      background: #ccc;
Creating variables for colors will make it easy to change our color scheme later.

2022-09-15 17:52 UTC, merged