Add on form database
Scott-Coates-Org/group-project-team-sapphire pull request #53
Opened 2022-09-16 21:17 UTC by jinchoo

2022-09-16 22:19 UTC, perennialAutodidact requested changes
Nice work! It looks like everything is set up to make the connection to Firebase.

The only thing I'm not seeing an onSubmit function for the AddOnForm. For now it can be included in the AddOnForm component. We can probably even remove the `onSubmit` prop from all the forms and just include the function in the component unless we find that we need to reuse that logic.

2022-09-16 22:19 UTC, perennialAutodidact commented on src/redux/addOnsSlice.js
> +  name: 'products',
The `name` attribute of this slice should be 'addOns' and not 'products' so it triggers the correct reducers in the slice

2022-09-16 22:19 UTC, perennialAutodidact commented on src/redux/addOnsSlice.js
> +      })
Stuff like this can be removed once the thunk logic works

2022-09-17 01:32 UTC, jinchoo commented on src/redux/addOnsSlice.js
> +  name: 'products',
Thank you for pointing that out.  I have changed the `name` attribute to 'addOns'.

2022-09-17 01:33 UTC, jinchoo commented
> Nice work! It looks like everything is set up to make the connection to Firebase.
> 
> The only thing I'm not seeing an onSubmit function for the AddOnForm. For now it can be included in the AddOnForm component. We can probably even remove the `onSubmit` prop from all the forms and just include the function in the component unless we find that we need to reuse that logic.

2022-09-17 01:36 UTC, jinchoo commented
> > Nice work! It looks like everything is set up to make the connection to Firebase.
> > The only thing I'm not seeing an onSubmit function for the AddOnForm. For now it can be included in the AddOnForm component. We can probably even remove the `onSubmit` prop from all the forms and just include the function in the component unless we find that we need to reuse that logic.

I don't know why closed the PR, but it is back.  
I have add the `onSubmit` to App.js.

2022-09-17 02:52 UTC, perennialAutodidact commented on src/App.js
> +                  dispatch(createAddOns(e))
It might make sense to remove the onSubmit from the form's props eventually, since it's unlikely that createAddOns will be dispatched anywhere else. We can take care of this later though

2022-09-17 02:52 UTC, perennialAutodidact approved these changes

2022-09-17 02:54 UTC, merged